name = "web-app-index"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "web-app-index-db"
database_id = "805553cc-a95f-43b6-b71d-6a9e49938a0c"

[[r2_buckets]]
binding = "R2"
bucket_name = "web-app-index-thumbnails"

[vars]
SITE_URL = "https://web-app-index.pages.dev"
